{"uuid": "16051042-d2c0-4db7-a8f1-0b20f188e903", "children": ["d7b05fac-2a4f-429d-98eb-54f4b0533ad5"], "befores": [{"name": "receipt", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable\n", "trace": "  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\conftest.py\", line 32, in receipt\n    response = orders.get_data_of_ing()\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\api_methods\\orders.py\", line 10, in get_data_of_ing\n    response = self.get_method(EndPoints.GET_DATA_ING)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 189, in impl\n    params = func_parameters(func, *a, **kw)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\utils.py\", line 231, in func_parameters\n    arg_spec = inspect.getfullargspec(func)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 1398, in getfullargspec\n    raise TypeError('unsupported callable') from ex\n"}, "steps": [{"name": "Получаем список ингредиентов", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable\n", "trace": "  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\api_methods\\orders.py\", line 10, in get_data_of_ing\n    response = self.get_method(EndPoints.GET_DATA_ING)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 189, in impl\n    params = func_parameters(func, *a, **kw)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\practicum\\diplom2\\Diplom_2\\.venv\\Lib\\site-packages\\allure_commons\\utils.py\", line 231, in func_parameters\n    arg_spec = inspect.getfullargspec(func)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Oleg\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 1398, in getfullargspec\n    raise TypeError('unsupported callable') from ex\n"}, "start": 1727011668011, "stop": 1727011668011}], "start": 1727011668011, "stop": 1727011668012}], "start": 1727011668011, "stop": 1727011668091}